version: "3.8"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - MONGO_URI=mongodb://mongo:27017/todo
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/app

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - mongo
    volumes:
      - .:/app

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  mongo_data:
