FROM python:3.11-slim

WORKDIR /app

# Copy all files to the container
COPY . /app/

# Install Celery dependencies
RUN pip install --no-cache-dir --timeout=300 -r requirements.txt

# Set environment variable for PostgreSQL URI
ENV POSTGRES_URI=postgresql://postgres:password@postgres:5432/todo

# Command to run Celery
CMD ["celery", "-A", "bot.tasks", "worker"]
